### ISSUE TITLE
Firefox 89 theme?

### ISSUE THREAD

**Issue by githubtefo** [PapirusDevelopmentTeam/thunderbird-theme-papirus#3]
Hi devs,
Would you extend this thunderbird theme to Firefox now that they changed a lot its interface and look more different to the rest of the papirus theme than before?

Thanks!

**Comment by varlesh** [comment]
Already doing:
![image](https://user-images.githubusercontent.com/8083855/122666710-115a7900-d1c0-11eb-9082-1d01e52d3dac.png)

**Comment by githubtefo** [comment]
that's great!!! Looks awesome! Great work!
Looking forward to use it.

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/firefox-papirus-icon-theme
